nginx:
    image: tutum/nginx
    ports:
        - "8000:80"
    links:
        - phpfpm
    volumes:
        - ./nginx/default:/etc/nginx/sites-available/default
        - ./nginx/default:/etc/nginx/sites-enabled/default

        - ./logs/error.log:/var/log/nginx/error.log
        - ./logs/access.log:/var/log/nginx/access.log

phpfpm:
    image: php:7-fpm
    ports:
        - "9000:9000"
    volumes:
        - ./code:/usr/share/nginx/html

mysql:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: admin

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  restart: always
  links:
    - mysql
  ports:
    - 8183:80
  environment:
    MYSQL_USERNAME: admin
    MYSQL_ROOT_PASSWORD: admin
    PMA_ARBITRARY: 1